name=StackChan Facial Control
version=0.1.0
author=botamochi
maintainer=botamochi<botamochi6277+github@gmail.com>
sentence=StackChan Facial Control for M5Stack
paragraph=See more on https://github.com/botamochi6277/stackchan-facial-control
category=Device Control
# url=https://platformio.org/lib/show/4529/StackChan-Facial-Control
architectures=esp32
includes=Avatar.h
depends=M5Unified
